### ISSUE TITLE
ERRO Error while running channelCreateAction: GetSigningIdentity returned error: user not found

### ISSUE THREAD

**Issue by ArvonHuang** [securekey/fabric-examples#16]
OS
MacOs 10.13

```
# fabric-sdk-go version (overridable)
FABRIC_SDK_GO_BRANCH    ?= master
FABRIC_SDK_GO_COMMIT    ?= 37201e914412e03b048f398ba3cdbf101515f9a3
```

➜  fabric-cli git:(master) ✗ docker ps -a 
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS              PORTS                                                      NAMES
851726b15b42        hyperledger/fabric-peer:x86_64-1.1.0      "peer node start"        22 minutes ago      Up 22 minutes       0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp, 7052/tcp   fabsdkgo_org1peer1_1
de52375c8461        hyperledger/fabric-peer:x86_64-1.1.0      "peer node start"        22 minutes ago      Up 22 minutes       0.0.0.0:7151->7151/tcp, 0.0.0.0:7153->7153/tcp, 7152/tcp   fabsdkgo_org1peer2_1
0173d1db03b2        hyperledger/fabric-peer:x86_64-1.1.0      "peer node start"        22 minutes ago      Up 22 minutes       0.0.0.0:9051->9051/tcp, 0.0.0.0:9053->9053/tcp, 9052/tcp   fabsdkgo_org2peer2_1
ac12e7224b79        hyperledger/fabric-peer:x86_64-1.1.0      "peer node start"        22 minutes ago      Up 22 minutes       0.0.0.0:8051->8051/tcp, 7052/tcp, 0.0.0.0:8053->8053/tcp   fabsdkgo_org2peer1_1
b9e8cfed5772        hyperledger/fabric-ca:x86_64-1.1.0        "sh -c 'fabric-ca-se…"   22 minutes ago      Up 22 minutes       7054/tcp, 0.0.0.0:8054->8054/tcp                           fabsdkgo_org2ca1_1
46dca7c4ee8a        hyperledger/fabric-ca:x86_64-1.1.0        "sh -c 'fabric-ca-se…"   22 minutes ago      Up 22 minutes       0.0.0.0:7054->7054/tcp                                     fabsdkgo_org1ca1_1
53996fe01763        hyperledger/fabric-baseos:x86_64-0.4.6    "tail -F anything"       22 minutes ago      Up 22 minutes                                                                  fabsdkgo_golangruntime_1
f1abd53d1d98        hyperledger/fabric-ccenv:x86_64-1.1.0     "tail -F anything"       22 minutes ago      Up 22 minutes                                                                  fabsdkgo_builder_1
e3733c3a75e9        hyperledger/fabric-orderer:x86_64-1.1.0   "orderer"                23 minutes ago      Up 22 minutes       0.0.0.0:7050->7050/tcp                                     fabsdkgo_orderer1_1
➜  fabric-cli git:(master) ✗ 

I run 
`go channel create --cid mychannel --txfile ../../fabric-sdk-go/test/fixtures/fabric/v1.1/channel/mychannel.tx --config ../../test/fixtures/config/config_test_local.yaml --cacert ../../test/fixtures/fabric/v1/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/admincerts/Admin@org1.example.com-cert.pem`
but it seems to find the cacert in path: /tmp/state-store/Admin@Org1MSP-cert.pem. However this cert perm dose not exist in my mac . It is a bug?

**Comment by ArvonHuang** [comment]
I change the config value in $GOPATH/src/github.com/securekey/fabric-examples/fabric-cli/test/fixtures/config/config_test_local.yaml

```
 credentialStore:
    # [Optional]. Used by user store. Not needed if all credentials are embedded in configuration
    # and enrollments are performed elswhere.
    #path: "/tmp/state-store"
    path: /Users/midea/apps/gopath//src/github.com/securekey/fabric-examples/fabric-cli/fabric-sdk-go/test/fixtures/fabric/v1/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/admincerts

    # [Optional]. Specific to the CryptoSuite implementation used by GO SDK. Software-based implementations
    # requiring a key store. PKCS#11 based implementations does not.
    cryptoStore:
      # Specific to the underlying KeyValueStore that backs the crypto key store.
     # path: /tmp/msp
     path: /Users/midea/apps/gopath/src/github.com/securekey/fabric-examples/fabric-cli/fabric-sdk-go/test/fixtures/fabric/v1/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
```

it fixed
